### ISSUE TITLE
Сбор данных пыльцевого мониторинга и создание сервисов для аллергиков

### ISSUE THREAD

**Issue by ivbeg** [infoculture/datatasks#17]
## Цель

Сделать удобный сервис мониторинга и прогнозирования аллергенов в России на основе текущих и архивных данных пыльцевого мониторинга используя данные с портала http://www.kestine.ru/monitoring.aspx как основу
## Задача
- создать базу мониторинга аллергенов
- сделать набор сервисов для пользователей таких как подписка и прогнозирование
## Требования
- открытый исходный код в Github под свободной лицензией
- межплатформенный код
## Пожелания
- открытые данные в формате CSV, JSON или XML
- публикация данных на хабе открытых данных hubofdata.ru
## Оценки трудоёмкости

Ожидаемое время на задачу должна занять не более 2-10 часов 
## Вспомогательные материалы:
- Текущие данные пыльцевого мониторинга http://www.kestine.ru/monitoring.aspx
- Архив пыльцевого мониторинга http://www.kestine.ru/monitoring/archive.aspx
## Примеры проектов для вдохновения
- Пыльцевой мониторинг в мобильном телефоне http://pollen.club/
- Allergy App http://www.pollen.com/android.asp
- 5 allergy apps http://mashable.com/2012/04/13/mobile-apps-seasonal-allergy-sufferers/
## Вопросы

Вопросы можно писать на ibegtin@infoculture.ru или в комментариях к этой задаче

**Comment by ermakove** [comment]
К сожалению указанный kestine.ru прекратил обновление базы в сентября 2015го...

**Comment by ivbeg** [comment]
К сожалению, да, но и эти данные актуальны. Обычно периоды опыления не очень меняются

**Comment by grande2020** [comment]
Архив тоже более недоступен.

**Comment by ivbeg** [comment]
Увы, придётся закрывать задачу, данных больше нет(

**Comment by grande2020** [comment]
P.S. Этим Яндекс немного занимается: https://yandex.ru/pogoda/moscow/maps/pollen
Плюс периодически приложение на iOS предупреждает о цветениях.

**Comment by ivbeg** [comment]
К сожалению это всё не про открытые данные
