### ISSUE TITLE
Извлечь данные из раздела "Социальный портрет преступности" на сайте crimestat.ru

### ISSUE THREAD

**Issue by ivbeg** [infoculture/datatasks#4]
## Цель

Создание массива данных по социальному портрету преступности
## Задача
- извлечь данные из HTML кода на сайте crimestat.ru - http://crimestat.ru/social_portrait
- структурировать данные в CSV и/ли JSON формате
- опубликовать данные на хабе открытых данных hubofdata.ru вручную или через API
## Требования
- открытый исходный код в Github под свободной лицензией
- межплатформенный код (возможность запуска на Linux/Windows)
- полнота данных - необходимо перенести всё по годам, регионам и отдельным графикам в их разрезе.
## Пожелания
- реализация в виде программы командной строки или веб-приложения
- возможность запуска на MacOSX
- использовать скриптовые языки такие как Python, Perl, R и другие.
## Оценки трудоёмкости

Задача должна занять не более 2 дней.
## Вспомогательные материалы:
- раздел с данными - http://crimestat.ru/social_portrait
- хаб открытых данных - http://hubofdata.ru

**Comment by ziavra** [comment]
данные http://hubofdata.ru/dataset/crime-social-portrait
скрипт https://github.com/ziavra/crimestat_parser

**Comment by ivbeg** [comment]
Очень круто, спасибо!
