### ISSUE TITLE
Визуализировать все таможни на карте России за 2 часа

### ISSUE THREAD

**Issue by Shorstko** [infoculture/datatasks#45]
## Цель

Визуализировать все таможенные органы с их контактными данными на карте России
## Задача
- взять набор открытых данных "Перечень таможенных органов" с сайта ФТС http://www.customs.ru/opendata/7730176610-p1tamorg/
- преобразовать адреса в геокоординаты при помощи Яндекс.Геокодер https://tech.yandex.ru/maps/doc/geocoder/desc/concepts/response_structure-docpage/
- установить CartoDB https://github.com/CartoDB/cartodb
- подготовить датасет в формате CSV или GeoJSON https://carto.com/docs/carto-engine/import-api/importing-geospatial-data/#geojson, загрузить в CartoDB и построить визуализацию
## Необходимые навыки
- базовое знание любого языка программирования для быстрой разработки
- базовое владение JSON/CSV, CartoDB, API
## Оценки трудоёмкости

Ожидаемое время на задачу 2 часа
## Приобретаемые навыки

Навык быстрой подготовки наборов данных, навык подготовки картографических визуализаций
## Вопросы

Вопросы можно писать на ibegtin@infoculture.ru или в комментариях к этой задаче

**Comment by e-kotov** [comment]
торможу: требуется просто загрузить итог в https://carto.com ? или развернуть где-то сервис?

**Comment by e-kotov** [comment]
Карта: https://ekotov.carto.com/viz/fae752ce-0126-11e7-878a-0ee66e2c9693/public_map
Данные: https://ekotov.carto.com/tables/ru_fcs_locations/public/

скрипт позже опубликую.
