### ISSUE TITLE
Составить рейтинг стран по объёмам поставки алкоголя в Россию за 1.5 часа

### ISSUE THREAD

**Issue by ivbeg** [infoculture/datatasks#49]
## Цель

Подсчитать, сколько алкоголя ввозится по странам в Российскую Федерацию по странам и объёму поставки.
## Задача
- взять справочник ТНВЭД https://github.com/infoculture/opencustoms/blob/master/data/tnved.csv и выбрать коды классификации, относящиеся к алкоголю 
- взять данные статистики внешней торговли https://github.com/infoculture/opencustoms/blob/master/data/TCBT.csv.zip (первоисточник http://stat.customs.ru/)
- выбрать данные, относящиеся к алкоголю, из данных статистики
- обработать данные 
- сгенерировать отчёт в CSV и HTML с визуализацией основных источников поставки алкоголя в Россию по странам
- дополнительные справочники доступны по ссылке https://github.com/infoculture/opencustoms/tree/master/data - ED.csv с единицами измерения и country.csv по странам
## Необходимые навыки
- базовое знание языка программирования Javascript и HTML 
- базовое владение CSV
## Оценки трудоёмкости

Ожидаемое время на задачу не более 1.5 часа
## Приобретаемые навыки

Навык быстрой визуализации бюджетных данных
## Вопросы

Вопросы можно писать на ibegtin@infoculture.ru или в комментариях к этой задаче

**Comment by Shorstko** [comment]
ссылка https://github.com/infoculture/opencustoms/data/TCBT.csv.zip нерабочая

**Comment by ivbeg** [comment]
Да. Вот верная https://github.com/infoculture/opencustoms/blob/master/data/TCBT.csv.zip

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.6.30&pv=5.1.1&source=email_footer_2] On Fri, Aug 12, 2016 at 8:43 PM, Elena Nikitina < notifications@github.com [notifications@github.com] > wrote:
ссылка https://github.com/infoculture/opencustoms/data/TCBT.csv.zip [https://github.com/infoculture/opencustoms/data/TCBT.csv.zip] нерабочая

**Comment by Shorstko** [comment]
исправлено в тексте задачи
