### ISSUE TITLE
Составить рейтинг "богатые театры / бедные театры" по данным госзаданий за 1.5 часа

### ISSUE THREAD

**Issue by ivbeg** [infoculture/datatasks#52]
## Цель

Составить рейтинг театров по госдоходам на основе данных портала bus.gov.ru
## Контекст

У bus.gov.ru есть недокументированное API для поиска и выгрузки данных по конкретной организации. Не обязательно обрабатывать весь их дамп с кучей XML файлов, можно взять только это API и выбрать данные только по театрам

Эндпоинты:
- поиск http://bus.gov.ru/public/agency/extendedSearchAgencyNew.json?action=&agency=%D0%B2%D1%8B%D1%81%D1%88%D0%B0%D1%8F%20%D1%88%D0%BA%D0%BE%D0%BB%D0%B0&documentTypes=A&okatoSubElements=false&orderAttributeName=rank&orderDirectionASC=false&page=1&pageSize=10&ppoSubElements=false&primaryActivitySubElements=false&searchTermCondition=and&secondaryActivitySubElements=false&vguSubElements=true&withBranches=true
- карточка организации http://bus.gov.ru/public/agency/agency.json?agency=169503
- запрос на получение баланса http://bus.gov.ru/public/agency/last-annual-balance-F0503721-info.json?agencyId=154828
- справочник видов организаций http://bus.gov.ru/public/nsi/vgu.json (код театрально-зрелищных организаций - 0614000)
- справочник регионов http://bus.gov.ru/public/getSelectorRegions.json
## Задача
- скачать и установить локально MongoDB - http://mongodb.org
- выгрузить в коллекцию MongoDB данные по театрам
- визуализировать и отрейтинговать датасет по бюджету
## Необходимые навыки
- базовое знание языка программирования Python
- базовое владение JSON, HTTP, API
## Оценки трудоёмкости

Ожидаемое время на задачу не более 1.5 часа
## Приобретаемые навыки

Навык быстрой подготовки наборов данных для дальнейшей работы
Навык работы с порталом bus.gov.ru
## Вопросы

Вопросы можно писать на ibegtin@infoculture.ru или в комментариях к этой задаче

**Comment by iradio** [comment]
Уточняю ссылку на API по театрам http://bus.gov.ru/public/agency/extendedSearchAgencyNew.json?action=&agency=%D0%B2%D1%8B%D1%81%D1%88%D0%B0%D1%8F%20%D1%88%D0%BA%D0%BE%D0%BB%D0%B0&documentTypes=A&okatoSubElements=false&orderAttributeName=rank&orderDirectionASC=false&page=1&pageSize=10&ppoSubElements=false&primaryActivitySubElements=false&searchTermCondition=and&secondaryActivitySubElements=false&vguSubElements=true&withBranches=true

**Comment by Archer-Lotos** [comment]
а где код?
