### ISSUE TITLE
Создать API на базе датасета внешней торговли за 1.5 часа

### ISSUE THREAD

**Issue by ivbeg** [infoculture/datatasks#56]
## Цель

Сделать API на базе датасета базы внешней торговли возвращающее JSON справочников и данных
## Задача
- взять данные статистики внешней торговли https://github.com/infoculture/opencustoms/blob/master/data/TCBT.csv.zip   (первоисточник http://stat.customs.ru/)
- взять справочник ТНВЭД https://github.com/infoculture/opencustoms/blob/master/data/tnved.csv и выбрать коды классификации относящиеся к урану 
- дополнительные справочники доступны по ссылке https://github.com/infoculture/opencustoms/tree/master/data - ED.csv с единицами измерения и country.csv по странам
- загрузить данные в базу MongoDB (http://mongodb.org)
- построить API с помощью любого движка
- выложить API в интернете
## Необходимые навыки
- базовое знание языка программирования Javascript, Python, Ruby или любой другой двиэлк
- базовое владение CSV
## Оценки трудоёмкости

Ожидаемое время на задачу не более 1.5 часа
## Приобретаемые навыки

Навык быстрого создания API на основе наборов данных
Навык работы с MongoDB
## Вопросы

Вопросы можно писать на ibegtin@infoculture.ru или в комментариях к этой задаче

**Comment by fukanchik** [comment]
B какой кодировке TCBT.csv?

**Comment by Shorstko** [comment]
@fukanchik, Dos866 (ASCII)
