### ISSUE TITLE
Извлечь данные из карты преступлений города Казани (http://umvd-kzn.geo4.me/) и преобразовать их в открытые данные

### ISSUE THREAD

**Issue by ivbeg** [infoculture/datatasks#8]
## Цель

Извлечь данные из карты преступлений города Казани (http://umvd-kzn.geo4.me/) и преобразовать их в открытые данные для использования на хакатонах и в других проектах. 
## Задача
- написать парсеры и выгрузить данные в форматах CSV и JSON
- загрузить данные в хаб открытых данных в удобном виде.
## Требования
- открытый исходный код в Github под свободной лицензией
- межплатформенный код (возможность запуска на Linux/Windows)
- предусмотреть перенос всех метаданных в CKAN в виде тегов и атрибутов
- переносить все данные в CKAN или на отдельный хостинг (например, в Github)
## Пожелания
- реализация в виде программы командной строки или веб-приложения
- возможность запуска на MacOSX
- использовать скриптовые языки такие как Python, Perl, R и другие.
## Оценки трудоёмкости

Задача должна занять не более 3 дней.
## Вспомогательные материалы:
- документация API CKAN - http://docs.ckan.org/en/latest/api/index.html
- карте преступлений Казани - http://umvd-kzn.geo4.me/

**Comment by alexknorre** [comment]
Ссылка на карту преступлений битая.

**Comment by ivbeg** [comment]
Да, похоже что за портал исчез:( придётся закрыть задачу поскольку других источников уже нет
